version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: token-labs-postgres
    environment:
      POSTGRES_DB: token_labs_db
      POSTGRES_USER: token_labs_user
      POSTGRES_PASSWORD: token_labs_password
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - token-labs-network

  redis:
    image: redis:7-alpine
    container_name: token-labs-redis
    ports:
      - "26379:6379"
    volumes:
      - redis_data:/data
    networks:
      - token-labs-network
    command: redis-server --appendonly yes

  app:
    build: .
    container_name: token-labs-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/token_labs_db
      SPRING_DATASOURCE_USERNAME: token_labs_user
      SPRING_DATASOURCE_PASSWORD: token_labs_password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - token-labs-network

volumes:
  postgres_data:
  redis_data:

networks:
  token-labs-network:
    driver: bridge
